// Blog posts. Dependency-free: each post's `body` is an array of blocks
// ({ t: "p" | "h2" | "ul", c }) rendered by BlogPost.jsx — no markdown lib,
// prerender-safe. Add a new post by adding an object here (newest first).
export const posts = [
  {
    slug: "choosing-coding-bootcamp-bengaluru-parents-guide",
    title: "How to choose a coding bootcamp in Bengaluru — a guardian's guide",
    description:
      "A short, honest guide for parents comparing coding institutes in Bengaluru: what to look for, what to ignore, and the questions that actually reveal quality.",
    date: "2026-09-04",
    author: "Rest Coder Academy",
    readMinutes: 9,
    body: [
      { t: "p", c: "Every parent in Bengaluru we speak with has the same two problems: dozens of coding institutes look identical from their websites, and the fee for a full-stack course can range from ₹15,000 to ₹1,50,000 for what claims to be the same outcome. This guide is what we tell parents in our own counselling calls — an honest checklist that cuts through the noise. We wrote it in the specific voice we use with the guardian of a first-year BCA student who has never had to evaluate a technical training programme before." },
      { t: "h2", c: "What to look for" },
      { t: "p", c: "The single strongest signal of a good coding course is not the syllabus, the classroom, or the marketing — it is whether the institute will name specific graduates and the specific companies they joined. If they cannot, do not assume the placement claim is real. If they can, verify one or two on LinkedIn." },
      { t: "p", c: "To make this concrete: our own placements page lists Sakshi at HCL Technologies as a Software Engineer, Sujith at SKAD IT Solutions in the same role, Prajwala R as a Test Automation Engineer at Quality Service Group, and Ashish Jadhav (who came in from a non-IT background in Maharashtra) as an SAP Hybris Developer at SAP Hybris itself. Four names, four companies, verifiable by anyone who wants to spend three minutes on LinkedIn. That is the format a real placement claim takes. \"100% placement, contact for details\" is not." },
      { t: "p", c: "Beyond that, five things matter more than anything else on their brochure:" },
      { t: "ul", c: [
        "Live classes with a real trainer — not recorded videos labelled \"self-paced\". Most students who drop off never restart the recording.",
        "The trainer's actual profile — name, current or last job, LinkedIn, at least one verifiable piece of work. If the institute hides this, they have a reason.",
        "Project-based assessment — your child builds real software during the course, not \"exercises\". Ask to see one graduate's project GitHub.",
        "Progress visibility for you — you should see weekly attendance and progress, not \"we'll let you know if there is a problem\".",
        "A written refund policy — a good institute will show you one on day zero.",
      ] },
      { t: "h2", c: "What to ignore" },
      { t: "p", c: "Air-conditioned classrooms, glossy brochures, big banners at metro stations, and the phrase \"industry-recognised certification\" (there is no such thing that actually helps in Indian hiring). Also, be careful of the two extremes: a fee that is very low usually means the course is prerecorded video with no real trainer time, and a very high fee usually means most of your money is going to advertising and franchise cuts, not to your child's learning. As a rough sanity check, ₹35,000 to ₹60,000 is the honest range for a live, project-based full-stack cohort in Bengaluru today." },
      { t: "h2", c: "The 5-minute phone call that tells you 80% of what you need" },
      { t: "p", c: "You do not need to visit five institutes to compare them. A five-minute phone call, with the same five questions asked in the same order, ranks them faster than a full tour. Ask exactly this:" },
      { t: "ul", c: [
        "\"Can you send me the LinkedIn profiles of three of your recent graduates?\" — a real institute has this ready and offers it within a day. If they need a week or ask why, keep looking.",
        "\"Who exactly will be teaching this batch, and what have they built or shipped?\" — the answer should be a name and a specific piece of work, not \"our expert team\".",
        "\"Can I see one week of your syllabus in detail, not just the topic list?\" — real curriculum reads as software you'd actually build; template curriculum reads as bullet points a marketing team assembled.",
        "\"What happens if my child falls behind or drops off — do I get told, and when?\" — the honest answer is a specific mechanism (weekly report, phone call, dashboard). \"We follow up\" is a non-answer.",
        "\"What does placement support actually mean? Do you refer, prep, or just introduce?\" — the honest answer is a concrete set of activities, not a percentage.",
      ] },
      { t: "p", c: "How they answer tells you more than the brochure ever will. A confident institute will answer specifically. A weak one will pivot to a sales pitch, ask which course you are interested in, or offer to have a \"senior counsellor\" call you back." },
      { t: "h2", c: "Red flags vs green flags" },
      { t: "p", c: "The pattern that separates real from theatrical, in one table you can screenshot:" },
      { t: "ul", c: [
        "🚩 \"100% placement guaranteed\" as a headline — nobody who has actually placed 100 students in a row uses this phrase.",
        "🚩 Trainer names hidden until you enrol — the moment you are quoted a fee, ask for the trainer's LinkedIn. If it is withheld, walk.",
        "🚩 A single testimonial video on the homepage with a cropped face and no name — real graduates give their full name, current role and company.",
        "🚩 Refund only in \"exceptional cases\" or \"at management discretion\" — a real policy has clear conditions and a clear timeline.",
        "🟢 Named graduates in the last six months, with roles and companies, findable on LinkedIn.",
        "🟢 A trainer profile that shows a real career — not \"10+ years' experience\" as the only detail.",
        "🟢 A written syllabus you can read before enrolling.",
        "🟢 A refund policy that survives a lawyer's read.",
      ] },
      { t: "h2", c: "The tour that tells you the truth" },
      { t: "p", c: "Ask to visit during an actual class, not on an appointment day. Look at three things: whether every student is actually working (not on their phone), whether the trainer is walking around answering questions, and whether the class is under 25 people. A crowded room where nobody is engaged is a warning, not an excuse. If the front desk tells you \"today is not a good day\", that itself is data — a functioning institute is happy to be seen on any weekday afternoon." },
      { t: "h2", c: "One last thing that costs you nothing to check" },
      { t: "p", c: "Search the institute's name on Google along with the word \"reviews\". Read three reviews from the last six months, not the star average. Pay particular attention to the negative ones — what specifically went wrong for those students, and how the institute responded. An institute that argues with a negative reviewer in public is telling you exactly how they will handle a problem with your child." },
      { t: "p", c: "If you would like a straight conversation about your child's background and goals — including candid comparisons to other institutes you are considering, and specific names of our alumni you can call and ask about their experience — come talk to us. We will not oversell." },
      { t: "p", c: "— Nikshep Kulli, Rest Coder Academy" },
    ],
  },
  {
    slug: "non-cs-background-to-full-stack-developer",
    title: "From a non-CS background to full-stack developer — an honest timeline",
    description:
      "How long it really takes to switch to full-stack development from a non-CS background, what each phase looks like, and how to know if you're on track.",
    date: "2026-09-04",
    author: "Rest Coder Academy",
    readMinutes: 8,
    body: [
      { t: "p", c: "A large share of the students we work with did not come from computer science. Commerce, mechanical, biotech, arts, testing, support, banking — the switch is common, and it works. Ashish Jadhav, who is now an SAP Hybris Developer at SAP Hybris, arrived at our door from a non-IT background in Maharashtra with no code on his laptop. But the timelines being sold online (\"become a developer in 3 months!\") are dishonest. Here is what it actually looks like, month by month." },
      { t: "h2", c: "Month 0–1: fundamentals" },
      { t: "p", c: "You learn one language, deeply. Not two, not five. Variables, functions, control flow, arrays, objects, and enough of the standard library to build small programs. If your course is any good, you write dozens of tiny programs in this phase — not read about them. Expect to feel slow. Everyone feels slow. This is the phase most self-learners quietly quit in." },
      { t: "p", c: "One useful heuristic for whether you're doing month one right: at the end of week four, could you write, without notes, a small program that reads a text file, counts how many times each word appears, and prints the top five? If yes, the foundation is landing. If no, you are consuming tutorials without producing anything, which is the most common trap." },
      { t: "h2", c: "Month 2–3: your first stack" },
      { t: "p", c: "You add a framework (Spring Boot, Django, or Node/Express) and a database, and you start building small applications that store and retrieve real data. By the end of this phase you should have built at least one CRUD application from scratch that you did not follow along to from a video. Something ugly is fine — original is what matters. A todo list, a bookmark manager, an expense tracker: pick something you actually use every day and build the version of it you wish existed." },
      { t: "p", c: "This is also the phase where imposter syndrome peaks. You will look at the framework's own source code and feel like you will never understand it. That feeling is not a sign you should quit — it is a sign you have moved past hello-world and started reading real code. Everyone who is now a senior engineer felt this way once. The way through it is more repetition, not more reading." },
      { t: "h2", c: "Month 4: the front end" },
      { t: "p", c: "HTML, CSS, JavaScript, then a framework (usually React). By the end of this phase you should be able to build a full-stack application — a front end that talks to an API you wrote, backed by a database — end-to-end. If your only framework is React and you have never written a page in plain HTML/CSS, go back a step. React is not a substitute for understanding how a browser renders a document." },
      { t: "h2", c: "Month 5: shipping" },
      { t: "p", c: "This is the phase most courses skip and most learners never finish on their own. You deploy your work somewhere real: a domain, a cloud host, a database that survives a restart. You add authentication that isn't broken, a payment integration, and error tracking. If you have never deployed anything, you are not a developer yet — you are a student. Shipping is the ceiling most people never cross without a structured push." },
      { t: "p", c: "This is also where interview stories come from. \"I built X and deployed it to Vercel/Cloudflare/AWS — here's the URL\" is the single most persuasive line in an entry-level interview. \"I completed 40 exercises on FreeCodeCamp\" is the least." },
      { t: "h2", c: "Month 6: interview readiness" },
      { t: "p", c: "You revise data structures and algorithms just enough to survive the coding round (not to become a competitive programmer), you polish two or three projects on your GitHub, and you start applying. Most switchers we work with land their first role somewhere between month 6 and month 8. A lucky few land in month 4. That is the honest range." },
      { t: "p", c: "Two examples from our own placements page: Sakshi went from a non-engineering background into a Software Engineer role at HCL Technologies; Sujith joined SKAD IT Solutions after the Java-and-Python cohort. Both are contactable on LinkedIn — the placements page has the links — and neither had CS degrees. What they had in common was consistent attendance and a shipped project by month five." },
      { t: "h2", c: "How to know you are on track" },
      { t: "ul", c: [
        "You can explain what a request does from browser to database, out loud, in your own words. If you have to look at your notes, you don't know it yet.",
        "You have shipped one thing publicly — even something ugly — that a stranger could use. A stranger's-eye test is different from your own.",
        "You are debugging by reading error messages and stack traces, not by asking a chatbot to fix it. Chatbots are good scaffolding, but if they are your only tool you are not developing the muscle interviewers hire for.",
        "You have written a README for a project that another beginner could follow. If you can teach a small piece of your work to somebody more junior than you, you have understood it.",
        "You've explained to at least one non-technical family member what you're doing, and they understood the shape of it. Being able to communicate technical work in plain language is a real signal, not a soft one.",
      ] },
      { t: "h2", c: "The two hardest months, and what to do in them" },
      { t: "p", c: "Month two and month five are where the highest number of people quit. Month two is when the novelty of writing your first program wears off and the compound difficulty of building your first small app becomes visible. Month five is when the plateau of \"I know how to build things but I have never deployed one\" turns into either a shipped project or a permanent \"almost-developer\" identity." },
      { t: "p", c: "The move that works, in both, is external accountability. A cohort you have to show up for, a mentor you have to email your project to, a study partner you have to answer to when you missed the day. Self-discipline is a beautiful thing when you already have it; if you are switching careers, you are almost certainly better served by structure than by discipline." },
      { t: "h2", c: "The pitfalls that don't get discussed" },
      { t: "p", c: "Three specific things people burn themselves on and rarely warn each other about:" },
      { t: "ul", c: [
        "Language-hopping. \"I'll try Python for a month, then Node, then Rust.\" Every switch resets the beginner clock. Pick one for six months and don't look at the others.",
        "Tutorial hell. If you can finish a tutorial but cannot start something from scratch, you have been watching, not learning. The fix is projects, not more tutorials.",
        "Comparing your month-3 to somebody's month-24. Twitter and LinkedIn are full of people who have been at this for years. The comparison is not useful — measure yourself against your last week, not against strangers.",
      ] },
      { t: "p", c: "If you are somewhere on this timeline and want structure around the parts that are hard to do alone — the deploying, the debugging, the second and third projects — that is exactly what a live, project-based course gives you. Talk to a counsellor if you would like a plan tailored to where you already are." },
      { t: "p", c: "— Nikshep Kulli, Rest Coder Academy" },
    ],
  },
  {
    slug: "live-coding-classes-vs-recorded-videos",
    title: "Live coding classes vs recorded videos — does it actually matter?",
    description:
      "The honest difference between live and recorded coding classes: completion rates, feedback loops, and why the cheap-recorded-video model rarely leads anywhere.",
    date: "2026-09-03",
    author: "Rest Coder Academy",
    readMinutes: 7,
    body: [
      { t: "p", c: "Every online coding course sells the same convenience: watch when you want, learn at your pace, complete on your schedule. It is a very seductive pitch. It is also the reason most online courses have completion rates in the low single digits. The uncomfortable truth about live vs recorded coding classes is this: it does not matter what you paid, it matters whether you finished." },
      { t: "p", c: "The most-cited number in the online-learning research is Katy Jordan's MOOC completion rate, which sits around 6–15% depending on the course. Massive courses at the top universities have completion rates that would embarrass a paid product. The tuition-free version of the same content on the same platform completes at a fraction of the paid version's rate. Price alone does not fix it. What fixes it is people knowing you." },
      { t: "h2", c: "What live classes actually give you" },
      { t: "p", c: "Three things a recording cannot: a real person who notices when you stop showing up, immediate feedback when your code is wrong for a reason you cannot see, and a room full of people whose expectation of your presence makes you keep showing up. That last one sounds small — it is not. It is the single biggest predictor of whether you finish." },
      { t: "p", c: "The feedback loop is the technical piece. A recording answers questions you already know how to ask. A live trainer answers the questions you didn't know were the important ones. When Sakshi (now at HCL Technologies) was mid-course, the most useful sessions weren't the scheduled classes — they were the fifteen minutes after class when a specific bug in her Spring Boot project turned into a five-minute walkthrough of what dependency injection actually does. That kind of moment does not exist in a video library." },
      { t: "h2", c: "Where recorded videos are fine" },
      { t: "p", c: "Quick reference for syntax you have forgotten. Learning a specific library's API. Getting a fast overview of a concept before you build on it. Free tutorial content on YouTube is genuinely great for these. What recorded content is not good for: your first exposure to a topic you have to actually master, or building the habit of shipping software. Use YouTube the way a working engineer does — as a reference — not the way a beginner does, which is as a substitute for practice." },
      { t: "h2", c: "Where the money goes" },
      { t: "p", c: "A recorded-video course can be sold to unlimited students at almost no marginal cost — which is why they can price at ₹5,000 to ₹20,000. A live cohort with a real trainer is priced by the trainer's time. When you see a \"live\" course sold at recorded-video prices, the \"live\" part is almost always doubtful: a huge classroom, a trainer racing through a slide deck, no real interaction, no follow-up. This is not a value judgment — it is a supply-side arithmetic point. There is no way to give a hundred students meaningful one-on-one feedback at ₹8,000 per head; the numbers do not close." },
      { t: "h2", c: "How to test whether a live course is actually live" },
      { t: "p", c: "Ask five questions, in this order:" },
      { t: "ul", c: [
        "\"What is the maximum batch size?\" Under 25 is a real cohort. Over 50 is a lecture hall. Over 100 is a webinar.",
        "\"Do trainers review student projects during the course, and how often?\" The honest answer is weekly, on a specific project you're building, with written comments you can point to later. \"Yes, ongoing\" is a non-answer.",
        "\"What happens if I miss a class or fall behind?\" A real live course has an active mechanism — a call, a catch-up session, a dashboard the trainer looks at. \"You'll get a recording\" means the class is effectively recorded even when it isn't.",
        "\"Can I sit in on one real class before enrolling?\" A confident live course will let you. A theatre one will find a reason not to.",
        "\"How many of the last cohort's students got jobs, and how long did it take on average?\" The number is less important than whether they have it at all. If they can't produce it, they don't track it, which means placement is not the operational priority they claim it is.",
      ] },
      { t: "h2", c: "The math on the price gap" },
      { t: "p", c: "The instinct that a ₹35,000 live course is somehow \"expensive\" compared to a ₹8,000 recorded one is worth pressure-testing with actual numbers. Suppose two students both start a course. The recorded one has a 10% chance of finishing (in line with MOOC averages). The live cohort has a 70% chance of finishing (in line with what small live cohorts see). Adjust for the probability of actually being job-ready at the end, and the cost per successful graduate flips: the ₹8,000 course costs ₹80,000 per graduate; the ₹35,000 course costs ₹50,000 per graduate. Price per unit of value, not price per unit of time." },
      { t: "h2", c: "The right answer for most people" },
      { t: "p", c: "If your goal is to actually change what you do for a living — not to add \"coding course\" to your resume — a live cohort with real accountability finishes you. Free videos plus solo grinding works too, but the drop-off rate is brutal. Only a small fraction of self-learners cross the finish line, and that fraction almost always has strong external accountability from somewhere else (a mentor, a peer group, a job that depends on it)." },
      { t: "p", c: "If you already have that accountability from elsewhere and just need the content, YouTube and freeCodeCamp are fine and free. If you don't, a live cohort is the accountability you're actually buying, and the content is a bonus. If you would like a straight opinion on what would suit you specifically, come talk to a counsellor — we'll give you an honest answer, including \"you don't need us\" when that's true." },
      { t: "h2", c: "The hybrid model that gets sold as \"the best of both\"" },
      { t: "p", c: "A lot of courses in Bengaluru now market a hybrid: recorded videos for the content, plus weekly live sessions for questions. The pitch is you get the flexibility of recorded plus the accountability of live. The honest reality is you usually get neither — the recorded content is not curated tightly enough to be efficient, and the weekly live sessions are too infrequent to create the daily rhythm that finishes people. The exception is when the weekly session is small (under fifteen students) and the trainer has visibility into who watched what — in that case, hybrid works. When it is a hundred-person Zoom call once a week, it is a recorded course with a marketing veneer." },
      { t: "h2", c: "What happens when a live class scales past its limit" },
      { t: "p", c: "The failure mode of a growing live coding course is that it silently becomes a recorded one. The trainer, faced with fifty students of mixed pace, records a standard walk-through, plays it in class, and answers questions afterwards. The class is technically live but the value of live has been quietly removed. The signal that this has happened: ask three current students what the last real bug the trainer helped them debug was. If none of them can name a specific bug from the last two weeks, the trainer is not doing live troubleshooting — they are broadcasting. A functioning live class produces named debugging stories weekly." },
      { t: "h2", c: "The one situation where recorded actually wins" },
      { t: "p", c: "There is one legitimate case where recorded beats live: you already know a language deeply and want to learn a specific new library or framework fast. In that case, structure and accountability matter less than search-ability — you want to jump around, replay a specific section, skip what you already know. This is exactly why senior engineers use recorded courses (Frontend Masters, Egghead) all the time. It is not how beginners should use them, and the difference is worth understanding before you buy something that was priced for the beginner market." },
      { t: "p", c: "— Nikshep Kulli, Rest Coder Academy" },
    ],
  },
  {
    slug: "what-placement-support-actually-means",
    title: "What \"placement support\" actually means — and how to spot fake claims",
    description:
      "\"100% placement\" is one of the most misused phrases in Indian coding education. Here's what real placement support looks like — and the questions that expose fake claims.",
    date: "2026-09-03",
    author: "Rest Coder Academy",
    readMinutes: 9,
    body: [
      { t: "p", c: "\"100% placement\" is one of the most misused phrases in Indian coding education. Almost nobody who advertises it actually means \"every student who finished got a job\" — most mean \"we referred everyone at least once\", or \"here is a certificate that says you completed the course\", or \"our numerator and denominator are different things and we won't tell you which\". Here is what real placement support actually looks like, and the questions that separate real from theatre." },
      { t: "h2", c: "What real placement support does" },
      { t: "p", c: "There is no magic here. Real placement support is a small set of unglamorous things done well, every batch:" },
      { t: "ul", c: [
        "Portfolio review — one-on-one, on your actual GitHub, not a template. If your \"portfolio\" is a stack of certificates, the review will end there.",
        "Resume review — specific to the role you are targeting, not a generic template. Written comments on your specific document, not a phone call that says \"looks good\".",
        "Mock interviews — technical and behavioural, with someone who has actually interviewed candidates. The best signal: the mock is scheduled with a specific person, on a specific date, and you get written feedback afterwards.",
        "Referrals into a maintained hiring network — companies the institute has an actual relationship with, not a shared job board. \"We'll circulate your resume\" is not the same as \"I emailed the HM at Company X on your behalf on Tuesday\".",
        "Post-placement follow-up — many students need help with the first 30 days on the job. Good institutes stay in touch. Not every institute does this, but the ones that do have visibly better long-term outcomes.",
      ] },
      { t: "h2", c: "What fake placement support looks like" },
      { t: "p", c: "A vague \"placement cell\" that turns out to be a WhatsApp group with a few links a week. A \"guaranteed job\" clause that turns out to be a certificate. A partnership page with 40 company logos and zero named graduates. A tour where nobody can name a specific student who was hired last quarter. \"Our alumni work at Google\" without any specific person — which usually means one distant graduate joined Google eight years ago as a support engineer." },
      { t: "p", c: "One test that reliably works: ask to see the hiring roster for the last two batches — names, roles, companies, month of hire. A real institute has this in a spreadsheet somebody can share the same day. A theatrical one will pivot to why they can't share it (privacy, in preparation, redesign of the placements page). \"We are protecting our students' privacy\" is usually a diplomatic way of saying \"there is no such spreadsheet\"." },
      { t: "h2", c: "The three questions that expose it" },
      { t: "p", c: "Ask these before you pay. Answers matter more than the way they are asked:" },
      { t: "ul", c: [
        "\"Can you show me the LinkedIn profiles of five graduates from the last two batches?\" — a real institute has this ready. Ideally within a day, verifiable in five minutes on LinkedIn.",
        "\"What percentage of your last batch was placed, and how do you count that?\" — the definition of \"placed\" is where dishonest numbers hide. A serious answer will define it clearly (roles ≥ ₹X CTC, within Y months of completion, excluding students who chose further study). Vague definitions are how you get to 100%.",
        "\"What is the median salary of a placed graduate?\" — median, not average. Averages are how you hide low outliers behind one big-package outlier. If the median is meaningfully lower than the average, that means most graduates land below what the marketing headline suggests.",
      ] },
      { t: "h2", c: "The four questions after those, if the first three passed" },
      { t: "p", c: "If the institute answers the first three cleanly, ask these next:" },
      { t: "ul", c: [
        "\"How long, on average, does it take from course completion to first offer?\" A real number is between 45 and 180 days for entry-level roles. \"Immediately after\" is either exceptional or a lie.",
        "\"What role did most of your last batch land in?\" A concentrated answer (\"12 of 20 got Java developer roles at service companies\") is a real answer. \"They got a mix of roles — some at product companies, some at startups, some in other fields\" is often diplomatic language for a low placement rate.",
        "\"What are you doing for students from the second-to-last batch who haven't been placed yet?\" This tests whether the support is a one-time push or a rolling responsibility.",
        "\"Who runs placement, and how long have they been in this role?\" If the answer is a name and a multi-year tenure, that is a real function. If it is \"we all pitch in\", it is not a function.",
      ] },
      { t: "h2", c: "What our own placements page looks like — and why" },
      { t: "p", c: "We deliberately do not publish a \"100% placement\" claim, because the honest number is never 100% — some students take a break, some pivot to further study, some take longer than the visible window. What we do publish is named graduates and their companies, on our placements page. As of the last batch review:" },
      { t: "ul", c: [
        "Ashish Jadhav — SAP Hybris Developer at SAP Hybris. Came in from a non-IT background in Maharashtra.",
        "Sakshi — Software Engineer at HCL Technologies. Non-CS background.",
        "Sujith — Software Engineer at SKAD IT Solutions. Java and Python full-stack cohort.",
        "Prajwala R — Test Automation Engineer at Quality Service Group. Java cohort.",
      ] },
      { t: "p", c: "Four names, four companies, all verifiable on LinkedIn in the time it takes to read this sentence. If a competing institute cannot produce the equivalent — actual names, actual companies, verifiable in three minutes — the placement claim is a marketing artefact, not an operational reality." },
      { t: "h2", c: "The role of trainers in placement, which nobody talks about" },
      { t: "p", c: "The single most under-appreciated factor in whether a student gets placed is whether the trainer has a personal network of hiring managers. A trainer who was recently in industry has three things a career trainer does not: recent context on what interviews actually cover, warm relationships with people who make hiring decisions, and the credibility to send a graduate's name in without it looking like spam. When you evaluate a course, look at the trainer's LinkedIn — not just their experience, but who they are connected to. If they are connected to hiring managers at the sort of companies you want to work at, the placement pipeline is real. If they are connected mostly to other trainers and students, it is a training network, not a hiring one." },
      { t: "h2", c: "One last honest note" },
      { t: "p", c: "No institute places 100% of their students, and any that claims to is either lying or defining \"placed\" so loosely that it is meaningless. What a good institute can honestly offer is: an active support function that helps most students land the first role, a written record of who they have placed and where, and continued help for those who take longer. If that is the kind of institute you are looking for, come talk to us. We are happy to name the graduates you can call and ask about their experience — and we are equally happy to tell you when we are not the right fit." },
      { t: "p", c: "— Nikshep Kulli, Rest Coder Academy" },
    ],
  },
  {
    slug: "java-vs-python-full-stack",
    title: "Java vs Python for full-stack: which should you learn first?",
    description:
      "A straight answer for beginners choosing between a Java and a Python full-stack path — what each is good at, who hires for it, and how to decide.",
    date: "2026-09-02",
    author: "Rest Coder Academy",
    readMinutes: 8,
    body: [
      { t: "p", c: "If you're starting out, \"Java or Python?\" is usually the first wall you hit. The honest answer: both lead to jobs, and the language matters less than whether you can actually build and ship something. But they do pull toward different work, so here's how to choose without overthinking it. We wrote this in the specific voice we use when a first-year student sits down for a counselling call with no code on their laptop and no idea whether they want to work at a service company or a startup." },
      { t: "h2", c: "What each is actually good at" },
      { t: "p", c: "Java is the workhorse of large, long-lived enterprise systems — banking, insurance, big product companies. It's strict, verbose, and that strictness is exactly why big teams like it: the compiler catches a lot before code ever runs. A Java full-stack path typically means Core & Advanced Java, Spring/Spring Boot, Hibernate, REST APIs, and a front end. Sakshi from our own placements went into a Java Software Engineer role at HCL Technologies via this exact path; Prajwala R went into Test Automation with a heavy Java skill set at Quality Service Group." },
      { t: "p", c: "Python is faster to write and reads almost like English, which is why it dominates data, scripting, automation, and AI, and is very strong for web too via Django. A Python full-stack path means Python, Django, REST APIs, and a modern front end. If you think you might drift toward data or AI later, Python gives you a head start. Sujith joined SKAD IT Solutions after our Java-and-Python combined cohort — his interview traction came from being credible in both, which is a real position to be in for early-career service-company roles." },
      { t: "h2", c: "Who's hiring for each, in Bengaluru specifically" },
      { t: "p", c: "In Bengaluru today, Java has the larger raw volume of openings — services companies (Infosys, TCS, Wipro, HCL, Capgemini) and product teams run enormous Java codebases and continue to hire steadily. If you spend an hour scrolling entry-level roles on Naukri, you will see roughly two Java openings for every one Python opening. Python roles are growing faster and skew toward startups, data teams, and AI-adjacent product companies — the numbers are smaller in absolute terms today but growing at a real rate. Neither is a dead end; both have healthy demand in 2026, and neither is going anywhere in the next decade." },
      { t: "p", c: "One nuance worth knowing: the salary distributions are different in shape, not just in level. Java entry-level roles cluster tightly around a common range (₹3.5–₹6 LPA for service companies, ₹6–₹10 LPA for product companies). Python entry-level roles have wider variance — many roles start lower (₹3–₹5 LPA for scripting/support) but the top of the range at data-heavy startups is higher (₹8–₹14 LPA). Java is safer on the median, Python has a fatter upper tail." },
      { t: "h2", c: "What recruiters actually ask in a first-round interview" },
      { t: "p", c: "The interview shape is different, which affects your prep. For a Java role, expect: OOP fundamentals in depth, Spring dependency injection, one JVM internals question (memory model, GC), one SQL query, one algorithm on strings or arrays. For a Python role, expect: language fundamentals (mutable vs immutable, list comprehensions, decorators), one Django/Flask specific question, one script-writing exercise (parse a file, hit an API), one algorithm on strings or arrays." },
      { t: "p", c: "The Python interview is usually less structured but more real-time — you might be asked to write code in a shared editor while the interviewer watches. The Java interview is usually more structured but more theoretical — you might be asked to explain a concept in depth before writing anything. Neither is easier. Different people find different formats comfortable." },
      { t: "h2", c: "So how do you actually decide?" },
      { t: "ul", c: [
        "Want the widest set of openings and don't mind strictness? Start with Java.",
        "Prefer to move fast, or curious about data/AI down the line? Start with Python.",
        "Coming from a testing/QA/support role? Java, likely — you'll speak the same language as the rest of your team and the transition is shorter.",
        "Coming from a data-analyst/Excel-heavy background? Python — the mental model already fits and you can lean on scripting familiarity.",
        "Genuinely torn? Pick either. The concepts — APIs, databases, HTTP, a front end, deploying to production — carry across. Learning your second language later is a matter of weeks, not months.",
      ] },
      { t: "h2", c: "What if you want to learn both?" },
      { t: "p", c: "It works, but only in sequence, not in parallel. The failure mode is trying to learn both in the same three-month window — you end up with shallow familiarity in each and depth in neither. The pattern that works: pick one, get to shipped-a-real-project competence (about four to five months), then add the second over the following two months. Learning your second language when you already know the first is significantly faster because the frameworks and mental models transfer." },
      { t: "p", c: "This is exactly the path Sujith took — Java first, then added Python, then applied for roles that valued both. It is not the fastest path to the first role (that would be picking one and stopping there) but it opens more doors after 18–24 months, which is when the difference between \"Java developer\" and \"full-stack developer with two languages\" starts to show up in salary bands." },
      { t: "h2", c: "The wrong reasons to pick" },
      { t: "p", c: "A few reasons people cite for one or the other that don't actually hold up:" },
      { t: "ul", c: [
        "\"Java is old.\" It's older than Python by three years. Neither is old in a way that matters.",
        "\"Python is for AI.\" Python is the AI language, but the AI job market is more competitive than the general web-developer market. Most Python jobs in Bengaluru are still web/backend, not ML.",
        "\"Java is verbose.\" True, but modern Java (17, 21) is far less verbose than Java 8. Records, pattern matching, and var declarations have narrowed the gap.",
        "\"My friend said pick X.\" Your friend's context is not your context. Their college, their circle, their target role are all different.",
      ] },
      { t: "h2", c: "The thing that actually gets you hired" },
      { t: "p", c: "Whichever you pick, employers don't hire a language — they hire someone who has built and shipped real things. That's why our Java and Python full-stack courses are project-based and live: you build working software, not slides, and ship it. If you'd like help choosing based on your background and goals, talk to a counsellor — it's a five-minute conversation that saves months." },
      { t: "p", c: "— Nikshep Kulli, Rest Coder Academy" },
    ],
  },
  {
    slug: "is-a-coding-course-worth-it-2026",
    title: "Is a coding course worth it in 2026? An honest look",
    description:
      "Coding courses get a bad rap for good reasons. Here's when one is genuinely worth it, when it isn't, and the questions to ask before you pay.",
    date: "2026-09-01",
    author: "Rest Coder Academy",
    readMinutes: 8,
    body: [
      { t: "p", c: "Plenty of people have paid for a coding course and gotten nothing out of it. So it's a fair question: in 2026, with free tutorials everywhere and AI that writes code, is a paid course still worth it? The honest answer is \"sometimes\" — and it depends far more on the course than on you. Here is the argument, made in both directions, and the questions to ask before you pay." },
      { t: "h2", c: "When a course is NOT worth it" },
      { t: "ul", c: [
        "It's all recorded videos and theory. You can get that free on YouTube.",
        "You never build anything real — just follow along and copy exercises.",
        "There's no accountability: nobody checks whether you're attending, learning, or progressing.",
        "\"Placement\" is a vague promise with no named students or companies behind it.",
        "The trainer's name and background are hidden until you enrol.",
        "The refund policy is either nonexistent or written to be impossible to trigger.",
      ] },
      { t: "p", c: "If a course looks like this, save your money. Self-study plus a few real projects will beat it. There is a version of the coding-education market that is genuinely predatory, and it exists on both the low end (₹5,000 recorded-video courses that promise nothing they can be held to) and the high end (₹1.5-lakh courses with impressive branding and hollow curriculum)." },
      { t: "h2", c: "When a course IS worth it" },
      { t: "p", c: "A good course buys you three things free tutorials can't: structure, feedback, and momentum. A live cohort with a real trainer means you're building actual software, getting your work reviewed, and being kept accountable so you don't quietly drift off in week three — which is where most self-learners stall." },
      { t: "p", c: "The best ones also close the loop to a job: real placement support, and honesty about outcomes. Ask to see named graduates and where they actually work. Our own graduates — Sakshi at HCL Technologies, Sujith at SKAD IT Solutions, Prajwala R at Quality Service Group, Ashish Jadhav at SAP Hybris — are all findable on LinkedIn in three minutes. That is the format an honest placement claim takes." },
      { t: "h2", c: "Does AI change the answer?" },
      { t: "p", c: "AI writes code, but it doesn't yet decide what to build, debug a broken production system, or take responsibility for shipping. Those judgment skills are exactly what get you hired — and they come from building real things with feedback, not from watching videos. If anything, AI raises the bar on \"can you actually ship?\", which is what a good, project-based course trains." },
      { t: "p", c: "The specific way AI has changed the entry-level market is worth understanding. Two years ago, being able to write a CRUD API in Node was a valid entry-level differentiator. Today, ChatGPT does that in eight seconds. The bar has moved to: can you architect a small system, debug it when the AI-generated code breaks, deploy it to a real environment, and explain your choices to a technical interviewer. Those skills do not come from prompting; they come from repeated exposure to real code under real constraints." },
      { t: "h2", c: "The five-year math nobody does" },
      { t: "p", c: "Suppose a coding course costs ₹35,000 and gets you into a first role at ₹5 LPA six months earlier than you would have made it on your own. That six months of extra earnings is roughly ₹2.5 lakh. Even if we assume you would have gotten there eventually via self-study, the paid course pays back in three months of the first role. The math looks even more favourable at higher entry salaries — a ₹35,000 course that gets you into a ₹9 LPA startup role six months earlier returns ₹4.5 lakh, which is a 12x return on the course fee." },
      { t: "p", c: "This math falls apart in exactly two conditions: the course does not actually get you a job (in which case you paid for nothing), or you would have gotten to the same role in the same time frame anyway (in which case the course was a nice-to-have, not a difference-maker). The interesting question is which condition you are in — and that is exactly what the questions in the next section are for." },
      { t: "h2", c: "Questions to ask before you pay" },
      { t: "ul", c: [
        "Will I build and ship real projects, or just do exercises?",
        "Is it live, with a real trainer I can verify?",
        "How do you keep students accountable and on track?",
        "Can you show me named graduates and the companies they joined?",
        "What exactly does \"placement support\" mean?",
        "What is your refund policy in writing?",
        "How many students are in a typical cohort, and how many trainers?",
        "What happens after I complete the course — is there any ongoing support?",
      ] },
      { t: "p", c: "That last set is how we'd want you to judge us too. Our courses are live and project-based, guardians can see a student's progress every week, and our placements page lists real graduates by name and company. If that's the kind of course you're after, come talk to us. If our answers to any of the questions above don't satisfy you, we'll be the first to say so and point you elsewhere." },
      { t: "h2", c: "A quick reality check on price" },
      { t: "p", c: "The Bengaluru market has courses ranging from ₹5,000 (recorded video, no trainer contact) to ₹1.5 lakh (heavily-branded programmes with celebrity mentors). The honest range for a live, project-based full-stack cohort with real placement support is roughly ₹30,000 to ₹60,000. Meaningfully above that and you are paying for marketing overhead; meaningfully below and something is being cut (usually trainer time or class size). Neither extreme reliably produces the outcome most students actually want, which is a first job in the industry within twelve months of starting." },
      { t: "h2", c: "The self-study path, when it works — and when it doesn't" },
      { t: "p", c: "The honest counter-argument to \"pay for a course\" is that plenty of successful engineers taught themselves from free content. That is true. What is also true is that the successful self-taught engineers usually had at least one of four things: prior programming exposure in some form, a technical friend who acted as a mentor by accident, a boring day job that gave them four hours a night to code, or a specific project (a startup, a hobby that needed software) that provided the accountability a course would otherwise have supplied." },
      { t: "p", c: "If you have none of those, self-study is not impossible but the drop-off statistics are brutal. The proportion of committed beginners who make it from \"first line of code\" to \"first developer job\" via pure self-study in under a year is well below 10% by any credible survey. It is not that a course magically fixes this; it is that the accountability, feedback and structure that a good course provides address the specific things that cause the drop-off. If you can generate those from your own life, you may not need a course. If you cannot, buying them is legitimate." },
      { t: "h2", c: "The five-year math, extended" },
      { t: "p", c: "The earlier ₹35,000 → ₹5 LPA math is a first-year calculation. The compounding piece is more interesting. A first role landed six months earlier does not just add six months of salary at the entry level; it also shifts your entire career timeline forward by six months. The typical mid-career salary jump (from ₹5 LPA to ₹15 LPA over four to five years) happens six months earlier, worth an additional ₹5 lakh over that window. And the peer network you build in a live cohort — other students who are also switching, and the trainer's network of hiring managers — pays off invisibly for years after in the form of the referrals that actually land you the second and third jobs, which are the ones that matter more for lifetime earnings than the first." },
      { t: "h2", c: "What we tell people who shouldn't take our course" },
      { t: "p", c: "A course is not the right choice for at least three types of people. First, if you are still in college and have a decent placement pipeline through the institution, use that first — most engineering colleges' first-round placements at HCL / Wipro / Infosys will hire you for Java roles without needing an external course. Second, if you have a full-time job you cannot compromise, a two-hour-a-week hobby is fine but a real cohort is not — you'll burn out and blame the course. Third, if you are already writing production code at a company (even as a QA who dabbles), your fastest path is asking your manager for a role change internally, not paying for a course that teaches you what you already partially know. We turn away roughly one in five callers for one of these three reasons — that number itself is a signal, and one we mention up front because pretending otherwise would erode the trust the rest of this post is trying to build." },
      { t: "p", c: "— Nikshep Kulli, Rest Coder Academy" },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug) || null;
}
